import Aboleth from "./models/Aboleth.js"
import BlueDragon from "./models/BlueDragon.js"
import CopperDragon from "./models/CopperDragon.js"
import DarkDragon from "./models/DarkDragon.js"
import Elemental from "./models/Elemental.js"